name: YLC Main Default
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflowId: 'YLC Main Default'