name: Yarn Lock Changes
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Lock Changes
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Yarn Lock Changes Detached Package
        uses: ./
        with:
          path: tests/detached/yarn.lock
          token: ${{ secrets.GITHUB_TOKEN }}