name: Yarn Lock Changes
on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn Lock Changes
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}